(ns code.migrate
  (:require [clojure.java.io :as io]
            [code.migrate.catalog :as catalog]
            [code.migrate.probe :as probe]
            [code.migrate.source :as source]
            [code.migrate.test :as test]))

(def +catalog-resource+ "code/migrate/catalog.edn")

(defn workspace-root
  "returns the configured Hara workspace root"
  {:added "4.1"}
  []
  (or (System/getenv "HARA_WORKSPACE_ROOT")
      "../../workspace"))

(defn catalog-path
  "returns Foundation's authoritative migration catalog path"
  {:added "4.1"}
  []
  (.getPath (io/file (io/resource +catalog-resource+))))

(defn load-catalog
  "loads the authoritative or an explicitly supplied migration catalog"
  {:added "4.1"}
  ([] (catalog/load-catalog (catalog-path)))
  ([path] (catalog/load-catalog path)))

(defn ensure-unit-kind
  [unit expected]
  (when-not (= expected (:unit/kind unit))
    (throw (ex-info "Migration unit has the wrong pathway"
                    {:expected expected
                     :unit/kind (:unit/kind unit)})))
  unit)

(defn analysis-result
  [result]
  (select-keys result
               [:unit/kind :source/path :target/path
                :source/checksum :output/checksum
                :applied :diagnostics :changed
                :operations :assertions :operation-correspondence]))

(defn reject-diagnostics
  [unit result]
  (if (seq (:diagnostics result))
    (throw (ex-info "Migration unit has blocking diagnostics"
                    {:unit (select-keys unit [:unit/kind :source/path])
                     :diagnostics (:diagnostics result)}))
    result))

(defn plan-source
  "returns the deterministic source-pathway migration plan"
  {:added "4.1"}
  ([unit]
   (plan-source unit (load-catalog)))
  ([unit migration-catalog]
   (ensure-unit-kind unit :source)
   (source/migrate-unit unit migration-catalog)))

(defn analyze-source
  "returns source-pathway diagnostics and evidence without generated bytes"
  {:added "4.1"}
  ([unit]
   (analyze-source unit (load-catalog)))
  ([unit migration-catalog]
   (analysis-result (plan-source unit migration-catalog))))

(defn migrate-source
  "returns generated source or rejects source-pathway diagnostics"
  {:added "4.1"}
  ([unit]
   (migrate-source unit (load-catalog)))
  ([unit migration-catalog]
   (reject-diagnostics unit (plan-source unit migration-catalog))))

(defn plan-test
  "returns the deterministic test-pathway migration plan"
  {:added "4.1"}
  ([unit]
   (plan-test unit (load-catalog)))
  ([unit migration-catalog]
   (ensure-unit-kind unit :test)
   (test/migrate-unit unit migration-catalog)))

(defn analyze-test
  "returns test-pathway diagnostics and evidence without generated bytes"
  {:added "4.1"}
  ([unit]
   (analyze-test unit (load-catalog)))
  ([unit migration-catalog]
   (analysis-result (plan-test unit migration-catalog))))

(defn migrate-test
  "returns generated tests or rejects test-pathway diagnostics"
  {:added "4.1"}
  ([unit]
   (migrate-test unit (load-catalog)))
  ([unit migration-catalog]
   (reject-diagnostics unit (plan-test unit migration-catalog))))

(defn analyze-unit
  "dispatches analysis to the unit's owning pathway"
  {:added "4.1"}
  ([unit]
   (analyze-unit unit (load-catalog)))
  ([unit migration-catalog]
   (case (:unit/kind unit)
     :source (analyze-source unit migration-catalog)
     :test (analyze-test unit migration-catalog)
     (throw (ex-info "Migration unit requires :source or :test kind"
                     {:unit/kind (:unit/kind unit)})))))

(defn plan-unit
  "dispatches planning to the unit's owning pathway"
  {:added "4.1"}
  ([unit]
   (plan-unit unit (load-catalog)))
  ([unit migration-catalog]
   (case (:unit/kind unit)
     :source (plan-source unit migration-catalog)
     :test (plan-test unit migration-catalog)
     (throw (ex-info "Migration unit requires :source or :test kind"
                     {:unit/kind (:unit/kind unit)})))))

(defn migrate-unit
  "dispatches generation to the unit's owning pathway"
  {:added "4.1"}
  ([unit]
   (migrate-unit unit (load-catalog)))
  ([unit migration-catalog]
   (case (:unit/kind unit)
     :source (migrate-source unit migration-catalog)
     :test (migrate-test unit migration-catalog)
     (throw (ex-info "Migration unit requires :source or :test kind"
                     {:unit/kind (:unit/kind unit)})))))

(defn migrate-pair
  "orchestrates independent source and test pathways"
  {:added "4.1"}
  ([source-unit test-unit]
   (migrate-pair source-unit test-unit (load-catalog)))
  ([source-unit test-unit migration-catalog]
   (when-not (= [:source :test]
                [(:unit/kind source-unit) (:unit/kind test-unit)])
     (throw (ex-info "Migration requires a source/test pair"
                     {:kinds [(:unit/kind source-unit)
                              (:unit/kind test-unit)]})))
   {:source (migrate-source source-unit migration-catalog)
    :test (migrate-test test-unit migration-catalog)}))

(defn verify-pair
  "verifies one emitted pair through lowered and native test paths"
  {:added "4.1"}
  [pair options]
  (probe/verify-pair pair
                     (assoc options
                            :migration/catalog
                            (or (:migration/catalog options)
                                (load-catalog)))))

(defn verify
  "backwards-compatible alias for verify-pair"
  {:added "4.1"}
  [pair options]
  (verify-pair pair options))