(ns play.ts-001-single-source-user-directory.build
  (:use [code.test :exclude [-main]])
  (:require [std.make :as make :refer [def.make]]
            [std.lang.model.spec-js.ts :as ts]
            [std.lang.model.spec-xtalk.mixer :as mixer]
            [play.ts-001-single-source-user-directory.main :as main]))

(def +gitignore+
  ["node_modules"])

(def +makefile+
  [[:.PHONY {:- ["build" "show-types" "show-js"]}]
   [:build
    ["@echo 'Artifacts are generated by def.make into .build/'"]]
   [:show-types
    ["@sed -n '1,160p' src/index.d.ts"]]
   [:show-js
    ["@sed -n '1,160p' src/index.js"]]])

(def +package+
  {"name" "ts-001-single-source-user-directory"
   "private" true
   "type" "module"
   "main" "src/index.js"
   "types" "src/index.d.ts"
   "exports" {"." "./src/index.js"}})

(def +expected-files+
  [".gitignore"
   "Makefile"
   "package.json"
   "src/index.js"
   "src/index.d.ts"])

(def +main-file+
  "src-build/play/ts_001_single_source_user_directory/main.clj")

(defn typescript-artifact
  [{:keys [runtime-output]}]
  {:output (ts/declaration-output-path runtime-output)
   :body   (-> +main-file+
               mixer/mix-file
               ts/emit-analysis-declarations)})

(def.make PROJECT
  {:github   {:repo "zcaudate/play.ts-001-single-source-user-directory"
              :description "Single-source xtalk project emitting JS plus d.ts"}
   :orgfile  "Main.org"
   :triggers '#{play.ts-001-single-source-user-directory.main}
   :sections {:setup [{:type :gitignore
                       :main +gitignore+}
                      {:type :makefile
                       :main +makefile+}
                      {:type :package.json
                       :main +package+}]}
   :default [{:type :module.single
              :lang :js
              :main 'play.ts-001-single-source-user-directory.main
              :file "index.js"
              :target "src"
              :emit {:artifacts [#'typescript-artifact]}}]})

(defn -main
  []
  (make/build-all PROJECT))

^{:eval false}
(fact "build the example into .build/"
  (make/build-all PROJECT))

^{:eval false}
(fact "show generated declaration output"
  (make/run PROJECT :show-types))

^{:eval false}
(fact "show generated javascript output"
  (make/run PROJECT :show-js))
