project_id = "local-min"

[api]
enabled = true
port = 55121
schemas = ["public", "storage", "graphql_public", "scratch", "scratch_v0", "scratch_v3"]
extra_search_path = ["public", "extensions", "scratch", "scratch_v0", "scratch_v3"]
max_rows = 1000

[db]
port = 55122
shadow_port = 55120
major_version = 15

[studio]
enabled = false

[inbucket]
enabled = false

[storage]
enabled = false

[analytics]
enabled = false

[edge_runtime]
enabled = false

[auth]
enabled = true
jwt_secret = "super-secret-jwt-token-with-at-least-32-characters-long"
site_url = "http://127.0.0.1:55121/auth/v1/health"
additional_redirect_urls = ["http://127.0.0.1:55121/*"]
