name: xtalk_packages
publish_to: none
environment:
  sdk: '>=3.6.0 <4.0.0'
workspace:
  - libs/xt-lang
  - libs/xt-event
  - libs/xt-substrate
  - libs/xt-mcp
  - libs/xt-net
  - libs/xt-db
  - libs/xt-ui