(ns js.gh-primer-brand
  (:require [std.lang :as l]
            [std.lib :as h]))

(l/script :js
  {:import [["@primer/react-brand" :as PrimerBrand]
            ["@primer/react-brand" :as PrimerBrand]]})

(h/template-entries [l/tmpl-entry {:type :fragment
                                   :base "PrimerBrand"
                                   :tag "js"}]
  [Accordion
   AccordionContent
   AccordionHeading
   AccordionRoot
   AccordionToggleColors
   ActionMenu
   ActionMenuButtonModes
   ActionMenuProvider
   ActionMenuSizes
   AnchorNav
   Animate
   AnimationContext
   AnimationProvider
   AnimationVariants
   Avatar
   AvatarShapes
   AvatarSizes
   Bento
   Box
   BoxBackgroundColors
   BoxBorderColorOptions
   BoxBorderRadiusOptions
   BoxBorderWidthOptions
   BoxSpacingValues
   BreadcrumbVariants
   Breadcrumbs
   BreakoutBanner
   BreakoutBannerBackgroundColors
   BreakpointSize
   Button
   ButtonGroup
   ButtonSizes
   ButtonVariants
   CTABanner
   CTABannerBackgroundColors
   CTAForm
   Card
   CardIconColors
   CardSkewEffect
   CardVariants
   Checkbox
   CheckboxGroup
   ColorModesEnum
   ComparisonTable
   DEFAULT_TEXTAREA_COLS
   DEFAULT_TEXTAREA_RESIZE
   DEFAULT_TEXTAREA_ROWS
   EyebrowBanner
   EyebrowBannerIconColors
   EyebrowBannerLabelColors
   FAQ
   FAQGroup
   Footnotes
   FootnotesItemTags
   FootnotesTags
   FormControl
   FrostedGlassVFX
   FrostedGlassVFXIntensity
   Grid
   Heading
   HeadingFontVariants
   HeadingLetterSpacing
   HeadingSizes
   HeadingStretch
   HeadingTags
   HeadingWeights
   Hero
   IDE
   IDEDefaultIconMap
   IDEFileExtensions
   Icon
   Image
   ImageBorderRadiusOptions
   InlineLink
   Label
   LabelColors
   LabelSizes
   Link
   LinkArrowDirections
   LinkSizes
   LinkVariants
   LogoSuite
   MinimalFooter
   OrderedList
   Pagination
   Pillar
   PillarIconColors
   PricingOptions
   Prose
   Radio
   RadioGroup
   River
   RiverAccordion
   RiverBreakout
   RiverContent
   RiverStoryScroll
   Section
   SectionBackgroundColors
   SectionIntro
   SectionPaddingVariants
   Select
   Stack
   StackAlignItemVariants
   StackDirectionVariants
   StackFlexWrapVariants
   StackJustifyContentVariants
   StackSpacingVariants
   Statistic
   StatisticSizes
   StatisticSpacingValues
   SubNav
   SubNavSubMenuVariants
   SubdomainNavBar
   Testimonial
   TestimonialQuoteMarkColors
   TestimonialVariants
   Text
   TextFontVariants
   TextInput
   TextRevealAnimation
   TextSizes
   TextTags
   TextVariants
   TextWeights
   Textarea
   ThemeContext
   ThemeProvider
   Timeline
   Tooltip
   TooltipContext
   UnorderedList
   VideoPlayer
   _Button
   _ComparisonTable
   actionMenuOverlaySides
   classMap
   defaultButtonSize
   defaultButtonVariant
   defaultCardIconColor
   defaultEyebrowBannerIconColor
   defaultFontVariant
   defaultFrostedGlassVFXIntensity
   defaultHeadingFont
   defaultHeadingTag
   defaultIconColor
   defaultIconSize
   defaultLabelColor
   defaultLabelSize
   defaultPillarIconColor
   defaultQuoteMarkColor
   defaultRiverAlign
   defaultRiverImageTextRatio
   defaultStackDirection
   defaultStackSpacing
   defaultTestimonialVariant
   defaultTextSize
   defaultTextTag
   defaultTextVariant
   iconColors
   iconSizeMap
   iconSizes
   namedIconSizes
   numericIconSizes
   useActionMenuContext
   useAnimation
   useSubNavContext
   useTheme
   useVideo
   useWindowSize])
