(ns xt.db.poc-v3.worker-threads
  "Node.js `worker_threads` version of the poc-v3 substrate/db setup.

   Unlike the browser SharedWorker variant, this runs entirely in Node's
   `:basic` runtime. The xt.db.node adaptor lives inside a worker thread;
   the main thread connects to it over the worker's `parentPort` and attaches
   proxy models just like the browser client does. No React, no browser APIs
   are required.

   The worker bootstrap script is generated by `xt.db.poc-v3.worker-threads-script`
   and should be written to disk before calling `connect-worker-threads`."
  (:require [hara.lang :as l]
            [xt.lang.spec-base]
            [xt.lang.spec-promise]
            [xt.lang.common-data]
            [xt.event.base-model]
            [xt.substrate]
            [xt.substrate.page-core]
            [xt.substrate.page-proxy]
            [xt.substrate.transport-browser]
            [xt.db.node.adaptor-base]
            [xt.db.node.adaptor-client]
            [xt.db.poc-v3.sharedworker :as sharedworker]))

(l/script :js
  {:require [[xt.lang.spec-base :as xt]
             [xt.lang.spec-promise :as promise]
             [xt.substrate :as substrate]
             [xt.substrate.page-proxy :as page-proxy]
             [xt.substrate.transport-browser :as transport-browser]
             [js.worker.link :as worker-link]
             [xt.db.poc-v3.sharedworker :as sharedworker]]})

(defn.js connect-worker-threads
  "Creates a client node, spawns the worker-thread server from `script-path`,
   and connects the two over the worker's MessagePort. Returns a promise of
   the client transport connection record."
  [script-path client-id]
  (var client (substrate/node-create {"id" client-id
                                      "spaces" {"room/a" {"state" {}}}}))
  (page-proxy/install client)

  (var link (worker-link/make-node-link script-path {"eval" false}))

  (return
   (transport-browser/connect-worker
    client
    {"source" link
     "transport_id" "worker"
     "wait_ready" true})))

(defn.js with-session
  "Runs callback inside a connected worker-thread session.
   `script-path` points to the worker file produced by
   `xt.db.poc-v3.worker-threads-script/write-worker-script!`.
   callback receives [client transport-id] and should return a promise."
  [script-path callback]
  (return
   (-> (-/connect-worker-threads script-path "poc-v3-client")
       (promise/x:promise-then
        (fn [conn]
          (var client (. conn ["node"]))
          (var transport-id (. conn ["transport_id"]))
          (return
           (-> (sharedworker/init-adaptor client transport-id)
               (promise/x:promise-then
                (fn [_]
                  (return (callback client transport-id)))))))))))
