(ns test-site.index
  (:use code.test)
  (:require [std.lib :as h]))

[[:chapter {:title "Welcome to Test Site"}
  [:section {:title "Introduction"}
   [:paragraph "This is a test site generated by code.doc."]
   [:code {:lang "clojure"}
    "(println \"Hello, World!\")"]]]]
