(ns lang-demos.ts-000-user-directory.build
  (:use [code.test :exclude [-main]])
  (:require [std.make :as make :refer [def.make]]
             [lang.model.builtin.spec-js.ts :as ts]
             [lang.typed.xtalk-analysis :as xtalk-analysis]
             [lang-demos.ts-000-user-directory.main :as main]
             [lang-demos.ts-000-user-directory.types :as types]))

(def +gitignore+
  ["node_modules"])

(def +makefile+
  [[:.PHONY {:- ["build" "show-types" "show-js"]}]
   [:build
    ["@echo 'Artifacts are generated by def.make into .build/demo/'"]]
   [:show-types
    ["@sed -n '1,160p' src/index.d.ts"]]
   [:show-js
    ["@sed -n '1,160p' src/index.js"]]])

(def +package+
  {"name" "ts-000-user-directory"
   "private" true
   "type" "module"
   "main" "src/index.js"
   "types" "src/index.d.ts"
   "exports" {"." "./src/index.js"}})

(def +expected-files+
  [".gitignore"
   "Makefile"
   "package.json"
   "src/index.js"
   "src/index.d.ts"])

(def +types-file+
  "src-build/lang_demos/ts_000_user_directory/types.clj")

(defn typescript-artifact
  [{:keys [runtime-output]}]
  {:output (ts/declaration-output-path runtime-output)
   :body   (-> +types-file+
               xtalk-analysis/analyze-file
               ts/emit-analysis-declarations)})

(def.make TS-000-USER-DIRECTORY
  {:build    ".build/demo/ts-000-user-directory"
   :github   {:repo "zcaudate/lang-demos.ts-000-user-directory"
              :description "Simple JS plus d.ts build generated from Clojure"}
   :orgfile  "Main.org"
   :triggers '#{lang-demos.ts-000-user-directory.main
                lang-demos.ts-000-user-directory.types}
   :sections {:setup [{:type :gitignore
                       :main +gitignore+}
                      {:type :makefile
                       :main +makefile+}
                      {:type :package.json
                       :main +package+}]}
   :default [{:type :module.single
              :lang :js
              :main 'lang-demos.ts-000-user-directory.main
              :file "index.js"
              :target "src"
              :emit {:artifacts [#'typescript-artifact]}}]})

(defn -main
  []
  (make/build-all TS-000-USER-DIRECTORY))

^{:eval false}
(fact "build the example into .build/demo/ts-000-user-directory"
  (make/build-all TS-000-USER-DIRECTORY))

^{:eval false}
(fact "show generated declaration output"
  (make/run TS-000-USER-DIRECTORY :show-types))

^{:eval false}
(fact "show generated javascript output"
  (make/run TS-000-USER-DIRECTORY :show-js))
