(ns play.js-002-substrate-scratch-v3.build
  (:use [code.test :exclude [-main]])
  (:require [std.make :as make :refer [def.make]]
            [play.js-002-substrate-scratch-v3.app]
            [play.js-002-substrate-scratch-v3.main]))

(def +index+
  ["<!doctype html>"
   "<html lang=\"en\">"
   "<head>"
   "  <meta charset=\"utf-8\" />"
   "  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\" />"
   "  <title>xt.substrate scratch-v3 playground</title>"
   "  <link rel=\"stylesheet\" href=\"./styles.css\" />"
   "</head>"
   "<body>"
   "  <main id=\"app\"></main>"
   "  <script type=\"module\" src=\"./app.js\"></script>"
   "</body>"
   "</html>"])

(def +styles+
  [":root { color-scheme: dark; font-family: ui-sans-serif, system-ui, sans-serif; background: #07110f; color: #eefaf5; }"
   "* { box-sizing: border-box; }"
   "body { margin: 0; min-height: 100vh; background: radial-gradient(circle at top left, #17382b, #07110f 52%); }"
   ".shell { width: min(1180px, 100%); margin: 0 auto; padding: 4rem 2rem 6rem; display: grid; gap: 1.2rem; }"
   ".hero { max-width: 820px; }"
   ".hero h1 { margin: 0; font-size: clamp(2.8rem, 7vw, 5.2rem); line-height: .98; letter-spacing: -.04em; }"
   ".hero p:last-child, .controls p, small { color: #9fc2b4; line-height: 1.55; }"
   ".eyebrow { color: #6fe7b8; font-size: .72rem; letter-spacing: .14em; text-transform: uppercase; }"
   ".demo-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(220px, 1fr)); gap: .9rem; }"
   ".demo-card, .panel { border: 1px solid #24463b; border-radius: 16px; background: rgba(13, 27, 23, .94); }"
   ".demo-card { color: inherit; text-align: left; padding: 1rem; display: grid; gap: .55rem; cursor: pointer; }"
   ".demo-card.active { border-color: #6fe7b8; box-shadow: 0 0 0 1px #6fe7b8 inset; }"
   ".demo-card code { color: #bfe8d7; overflow-wrap: anywhere; }"
   ".panel { padding: 1.25rem; }"
   ".controls { display: grid; gap: .7rem; }"
   "label { display: grid; gap: .4rem; color: #9fc2b4; }"
   "input { border: 1px solid #24463b; border-radius: 10px; background: #06100d; color: inherit; padding: .75rem; font: inherit; }"
   ".columns { display: grid; grid-template-columns: repeat(2, minmax(0, 1fr)); gap: 1rem; }"
   "pre { margin: 0; padding: 1rem; border-radius: 12px; background: #06100d; overflow: auto; white-space: pre-wrap; word-break: break-word; }"
   "@media (max-width: 760px) { .columns { grid-template-columns: 1fr; } .shell { padding: 2.5rem 1rem 4rem; } }"])

(def +makefile+
  [[:.PHONY {:- ["build" "start"]}]
   [:build
    ["@echo 'Artifacts are generated by def.make into .build/'"]]
   [:start
    ["python3 -m http.server 8080 --directory public"]]])

(def +expected-files+
  ["Makefile"
   "public/index.html"
   "public/styles.css"
   "public/app.js"])

(def.make PROJECT
  {:tag "play-js-002-substrate-scratch-v3"
   :build ".build/play-js-002-substrate-scratch-v3"
   :triggers '#{play.js-002-substrate-scratch-v3.app
                play.js-002-substrate-scratch-v3.main}
   :sections {:setup [{:type :makefile
                       :main +makefile+}
                      {:type :raw
                       :target "public"
                       :file "index.html"
                       :main +index+}
                      {:type :raw
                       :target "public"
                       :file "styles.css"
                       :main +styles+}]}
   :default [{:type :module.directory
              :lang :js
              :search ["src-build"]
              :main 'play.js-002-substrate-scratch-v3.app
              :target "public"
              :emit {:code {:link {:path-suffix ".js"
                                   :root-prefix "./"}}}}]})

(defn -main
  []
  (make/build-all PROJECT))

^{:eval false}
(fact "build the scratch-v3 substrate playground"
  (make/build-all PROJECT))
