(ns play.tui-002-game-of-life.build
  (:use [code.test :exclude [-main]])
  (:require [hara.lang :as  l]
            [js.blessed.project :as blessed-project]
            [std.lib :as h]
            [std.make :as make :refer [def.make]]
            [js.webpack :as webpack]
            [play.tui-002-game-of-life.main :as main]))

(def +makefile+
  [[:.PHONY {:- ["build" "start" "dev"]}]
   [:build
    ["@echo 'Artifacts are generated by def.make into .build/'"]]
   [:start
    ["node dist/main.js"]]
   [:dev
    ["npx webpack --watch"]]])

(def +expected-files+
  [".gitignore"
   "Makefile"
   "package.json"
   "webpack.config.js"
   "src/main.js"])

(def +package+
  (:main (blessed-project/module-package-json
          "tui-002-game-of-life"
          {"main" "dist/main.js"})))

(def.make PROJECT
  {:github   {:repo "zcaudate/play.tui-002-game-of-life"
              :description "Simple Blessed TUI Game of Life Example"}
   :orgfile  "Main.org"
   :triggers '#{play.tui-002-game-of-life.main}
   :sections {:setup  [{:type :gitignore
                        :main ["dist" "node_modules" "out"]}
                       {:type :makefile
                        :main +makefile+}
                       {:type :package.json
                        :main +package+}
                       webpack/+node-basic+]}
    :default  [{:type :module.single
                :lang :js
                :main 'play.tui-002-game-of-life.main
                :file "main.js"
                :target "src"}]})

(def PROJECT_COMMONJS PROJECT)
(def PROJECT_ESM PROJECT)

(def +init+
  nil)

(defn -main
  []
  (std.make/build-all play.tui-002-game-of-life.build/PROJECT)
  (make/gh:dwim-init PROJECT))

^{:eval false
  ;;
  ;; BUILD SETUP
  ;;
  }
(fact "Code FOR PROJECT SETUP" 

  (make/build-all PROJECT))

^{:eval false
  ;;
  ;; BUILD SETUP
  ;;
  }
(fact "Code FOR PROJECT SETUP" 

  (make/run:init PROJECT))

^{:eval false
  ;;
  ;; RUN DEV
  ;;
  }
(fact "Code FOR PROJECT SETUP" 

  (make/run:dev PROJECT))

^{:eval false
  ;;
  ;; GH INITAL SETUP
  ;;
  :ui/action [:GITHUB :SETUP]}
(fact "initial setup of repo from github"

  (make/gh:dwim-init PROJECT))

^{:eval false
  ;;
  ;; GH PUSH NEWEST
  ;;
  :ui/action [:GITHUB :PUSH]}
(fact "pushes changes to github"

  (make/gh:dwim-push PROJECT))
