name: Build

on: push

jobs:
  run-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Running Tests
        run:  docker run --network host -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):$(pwd) -w $(pwd) ghcr.io/zcaudate/testing-foundation:main lein test
        
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: test
          POSTGRES_PASSWORD: postgres
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
        ports:
          - 5432:5432

  build-container:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/zcaudate/testing-foundation:main
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Installing Jars
        run: |
          lein install
          cp -r /root/.m2/repository/foundation docker/foundation

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Extract metadata (tags, labels) for Docker
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/zcaudate/foundation-base

      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: docker
          tags: '${{ steps.metadata.outputs.tags }}'
          labels: '${{ steps.metadata.outputs.labels }}'
          push: true
          
