name: Build

on: [push, repository_dispatch, workflow_dispatch]

jobs:

  build-container:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/zcaudate/testing-foundation:main
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Installing Jars
        run: |
          lein install
          cp -r /root/.m2/repository/foundation docker/foundation

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Extract metadata (tags, labels) for Docker
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/zcaudate/foundation-base

      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: docker
          tags: '${{ steps.metadata.outputs.tags }}'
          labels: '${{ steps.metadata.outputs.labels }}'
          push: true
          
      - name: Notify zcaudate/foundation-embed
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.GH_TOKEN }}
          repository: zcaudate/foundation-embed
          event-type: notify
