name: Format docs PR

on:
  pull_request:
    branches: [main]
    paths:
      - .github/workflows/format-docs-pr.yml

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: echo ready
