name: Run Code

on: [push, repository_dispatch, workflow_dispatch]

env:
  LEIN_JVM_OPTS: -Xms512m -Xmx3g -XX:+UseG1GC -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp

jobs:
  
  run-incomplete:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Run Incomplete
        run: >
          docker run --network host 
          -e "LEIN_JVM_OPTS=${LEIN_JVM_OPTS}"
          -v /var/run/docker.sock:/var/run/docker.sock 
          -v $(pwd):$(pwd) 
          -w $(pwd) 
          ghcr.io/zcaudate-xyz/infra-foundation-clean:ci lein incomplete
          
  run-group-tests:
    name: Run Tests - ${{ matrix.name }}
    runs-on: ubuntu-latest
    timeout-minutes: 40
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: hara
            target: "[hara]"
            command: lein test :with "[hara]"
          - name: std
            target: "[std]"
            command: lein test :with "[std]"
          - name: xt
            target: "[xt.]"
            command: lein test :with "[xt.]"
          - name: code
            target: "[code]"
            install_js_parser: true
            command: lein test :with "[code]"
          - name: script, net, math, lib, jvm
            target: "[script net math lib jvm]"
            command: lein test :with "[script net math lib jvm]"
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install JS parser dependencies
        if: matrix.install_js_parser == true
        working-directory: src-training/scripts/js_parser
        run: npm ci
        
      - name: Run Tests - ${{ matrix.name }}
        run: >
          docker run --network host
          -e "LEIN_JVM_OPTS=${LEIN_JVM_OPTS}"
          -v /var/run/docker.sock:/var/run/docker.sock
          -v $(pwd):$(pwd)
          -w $(pwd)
          ghcr.io/zcaudate-xyz/infra-foundation-clean:ci
          bash -lc "set -euxo pipefail &&
          apt-get update &&
          apt-get install -y --no-install-recommends lua5.4 python3 python3-pip &&
          ${{ matrix.command }}"
        
    services:
      postgres:
        image: ghcr.io/zcaudate-xyz/infra-db:main
        env:
          POSTGRES_DB: test
          POSTGRES_PASSWORD: postgres
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
        ports:
          - 5432:5432

  run-lang-tests:
    name: Run Tests - ${{ matrix.lang }}
    runs-on: ubuntu-latest
    timeout-minutes: 40
    strategy:
      fail-fast: false
      matrix:
        include:
          - lang: js
            install_js_parser: true
          - lang: lua
          - lang: python
          - lang: dart
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install JS parser dependencies
        if: matrix.install_js_parser == true
        working-directory: src-training/scripts/js_parser
        run: npm ci
        
      - name: Run Tests - ${{ matrix.lang }}
        run: >
          docker run --network host 
          -e "LEIN_JVM_OPTS=${LEIN_JVM_OPTS}"
          -v /var/run/docker.sock:/var/run/docker.sock 
          -v $(pwd):$(pwd) 
          -w $(pwd) 
          ghcr.io/zcaudate-xyz/infra-foundation-clean:ci
          lein test :with "${{ matrix.lang }}"
        
    services:
      postgres:
        image: ghcr.io/zcaudate-xyz/infra-db:main
        env:
          POSTGRES_DB: test
          POSTGRES_PASSWORD: postgres
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
        ports:
          - 5432:5432


  run-xtbench-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    strategy:
      fail-fast: false
      matrix:
        include:
          - lang: dart
            image: ghcr.io/zcaudate-xyz/infra-foundation-xtbench-dart:ci
          - lang: ruby
            image: ghcr.io/zcaudate-xyz/infra-foundation-xtbench-ruby:ci

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log into GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.GH_USER }}
          password: ${{ secrets.GH_TOKEN }}

      - name: Run xtbench tests - ${{ matrix.lang }}
        run: >
          docker run --network host
          -e "LEIN_JVM_OPTS=${LEIN_JVM_OPTS}"
          -v /var/run/docker.sock:/var/run/docker.sock
          -v $(pwd):$(pwd)
          -w $(pwd)
          ${{ matrix.image }}
          lein test :with xtbench.${{ matrix.lang }}

    services:
      postgres:
        image: ghcr.io/zcaudate-xyz/infra-db:main
        env:
          POSTGRES_DB: test
          POSTGRES_PASSWORD: postgres
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
