name: Run Tests

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run Unit Tests
      run: docker run --privileged -v $(pwd):$(pwd) -v /var/run/docker.sock:/var/run/docker.sock --workdir $(pwd) ghcr.io/zcaudate/testing-foundation:main /usr/bin/entrypoint.sh lein test
      
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: scratch
          POSTGRES_PASSWORD: postgres
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      
